<?php

namespace IL\CoreBundle\Repository;

/**
 * SouscriptionBanqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouscriptionBanqueRepository extends \Doctrine\ORM\EntityRepository
{
}
