<?php

namespace IL\CoreBundle\Repository;

/**
 * SouscriptionMobileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouscriptionMobileRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByStatutLinkage($statut, $carte, $operateur, $start, $end)
    {
        //dump($start); exit;
        $qb = $this->createQueryBuilder('s')
            ->where('s.statutLiaison = :statut')
            ->andWhere('s.numeroCarte = :carte')
            ->andWhere('s.operateur = :operateur')
            ->setParameters([
                'statut' => $statut,
                'operateur' => $operateur,
                'carte' => $carte,

            ]);
        $result = $qb->getQuery()->getResult();

       // dump($result); exit;
        return $result;
    }

    public function getByTypeOperation($type, $carte, $operateur, $start, $end)
    {
        //dump($start); exit;
        if($type == 1)
        {
            if($carte != "")
            {
                $sql = "select * from transfert WHERE trans = 'c2w'  and source = '$carte' and created_at BETWEEN '$start 00:00:00' and '$end 23:59:59'";
                $connexion = $this->_em->getConnection();
                $query = $connexion->prepare($sql);
                $query->execute();
                $result = $query->fetchAll();

                //dump($result); exit;
                return $result;
            }
            else{
                $sql = "select * from transfert WHERE trans = 'c2w' and  created_at BETWEEN '$start 00:00:00' and '$end 23:59:59'";
                $connexion = $this->_em->getConnection();
                $query = $connexion->prepare($sql);
                $query->execute();
                $result = $query->fetchAll();

                //dump($result); exit;
                return $result;
            }

        }
        else{
            if($carte != '')
            {
                $sql = "select * from transfert WHERE  trans = 'w2c'  and beneficiaire = '$carte' and created_at BETWEEN '$start 00:00:00' and '$end 23:59:59' ";
                $connexion = $this->_em->getConnection();
                $query = $connexion->prepare($sql);
                $query->execute();
                $result = $query->fetchAll();

                //dump($result); exit;
                return $result;
            }
            else{
                $sql = "select * from transfert WHERE  trans = 'w2c' and created_at BETWEEN '$start 00:00:00' and '$end 23:59:59' ";
                $connexion = $this->_em->getConnection();
                $query = $connexion->prepare($sql);
                $query->execute();
                $result = $query->fetchAll();

                //dump($result); exit;
                return $result;
            }
        }

       // dump($result); exit;

    }

    public function NumberOfTransfert()
    {
        $sql = "select count(id) as nbre from transfert ";
        $connexion = $this->_em->getConnection();
        $query = $connexion->prepare($sql);
        $query->execute();
        $result = $query->fetchAll();

       // dump($result[0]); exit;

        return $result[0];
    }
}
