fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: IL\UserBundle\Entity\User
    from_email:
        address: sidibesekouassane@gmail.com
        sender_name: ILAFIA