<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOnaqaxj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOnaqaxj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOnaqaxj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOnaqaxj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerOnaqaxj\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Onaqaxj',
    'container.build_id' => '9f246e1d',
    'container.build_time' => 1539962088,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOnaqaxj');
