<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDn88akp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDn88akp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDn88akp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDn88akp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDn88akp\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Dn88akp',
    'container.build_id' => 'f95cdb23',
    'container.build_time' => 1538672466,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDn88akp');
